name: create growtopia accounts

on:
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x createidv2
      - run: ./createidv2
