name: create growtopia accounts

on:
  push:
    paths:
      - 'config.json'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x createidv2
      - run: ./createidv2
